// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wine_cellar.Contexts;

#nullable disable

namespace Winecelar.Migrations
{
    [DbContext(typeof(WineContext))]
    [Migration("20221212103929_V5")]
    partial class V5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wine_cellar.Entities.Appelation", b =>
                {
                    b.Property<int>("AppelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppelationId"));

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("KeepMax")
                        .HasColumnType("int");

                    b.Property<int>("KeepMin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppelationId");

                    b.ToTable("Appelations");

                    b.HasData(
                        new
                        {
                            AppelationId = 1,
                            Color = 0,
                            KeepMax = 10,
                            KeepMin = 5,
                            Name = "Bordeaux"
                        },
                        new
                        {
                            AppelationId = 2,
                            Color = 0,
                            KeepMax = 6,
                            KeepMin = 4,
                            Name = "Loire"
                        },
                        new
                        {
                            AppelationId = 3,
                            Color = 0,
                            KeepMax = 20,
                            KeepMin = 10,
                            Name = "Bordeaux, Grands crus"
                        },
                        new
                        {
                            AppelationId = 4,
                            Color = 0,
                            KeepMax = 10,
                            KeepMin = 5,
                            Name = "Sud-Ouest"
                        },
                        new
                        {
                            AppelationId = 5,
                            Color = 0,
                            KeepMax = 8,
                            KeepMin = 5,
                            Name = "Languedoc & Provence"
                        },
                        new
                        {
                            AppelationId = 6,
                            Color = 0,
                            KeepMax = 6,
                            KeepMin = 4,
                            Name = "Côtes du Rhône"
                        },
                        new
                        {
                            AppelationId = 7,
                            Color = 0,
                            KeepMax = 20,
                            KeepMin = 10,
                            Name = "Cotes du Rhônes, Grands Crus"
                        },
                        new
                        {
                            AppelationId = 8,
                            Color = 0,
                            KeepMax = 5,
                            KeepMin = 4,
                            Name = "Beaujolais"
                        },
                        new
                        {
                            AppelationId = 9,
                            Color = 0,
                            KeepMax = 8,
                            KeepMin = 5,
                            Name = "Beaujolais, Crus"
                        },
                        new
                        {
                            AppelationId = 10,
                            Color = 0,
                            KeepMax = 10,
                            KeepMin = 5,
                            Name = "Bourgogne, Saône-et-Loire"
                        },
                        new
                        {
                            AppelationId = 11,
                            Color = 0,
                            KeepMax = 20,
                            KeepMin = 10,
                            Name = "Bourgogne, Côte-d'Or"
                        },
                        new
                        {
                            AppelationId = 12,
                            Color = 2,
                            KeepMax = 4,
                            KeepMin = 3,
                            Name = "Loire, Sec"
                        },
                        new
                        {
                            AppelationId = 13,
                            Color = 2,
                            KeepMax = 20,
                            KeepMin = 10,
                            Name = "Loire, moelleux et liquoreux"
                        },
                        new
                        {
                            AppelationId = 14,
                            Color = 2,
                            KeepMax = 8,
                            KeepMin = 5,
                            Name = "Bordeaux, sec"
                        },
                        new
                        {
                            AppelationId = 15,
                            Color = 2,
                            KeepMax = 20,
                            KeepMin = 15,
                            Name = "Bordeaux, liquoreux"
                        },
                        new
                        {
                            AppelationId = 16,
                            Color = 2,
                            KeepMax = 5,
                            KeepMin = 4,
                            Name = "Sud-Ouest, sec"
                        },
                        new
                        {
                            AppelationId = 17,
                            Color = 2,
                            KeepMax = 15,
                            KeepMin = 10,
                            Name = "Sud-Ouest, liquoreux"
                        },
                        new
                        {
                            AppelationId = 18,
                            Color = 2,
                            KeepMax = 3,
                            KeepMin = 3,
                            Name = "Languedoc & Provence"
                        },
                        new
                        {
                            AppelationId = 19,
                            Color = 2,
                            KeepMax = 4,
                            KeepMin = 3,
                            Name = "Côtes du Rhône"
                        },
                        new
                        {
                            AppelationId = 20,
                            Color = 2,
                            KeepMax = 4,
                            KeepMin = 4,
                            Name = "Bourgogne, Saône-et-Loire"
                        },
                        new
                        {
                            AppelationId = 21,
                            Color = 2,
                            KeepMax = 10,
                            KeepMin = 7,
                            Name = "Bourgogne, Côte-d'Or"
                        },
                        new
                        {
                            AppelationId = 22,
                            Color = 2,
                            KeepMax = 20,
                            KeepMin = 8,
                            Name = "Jura"
                        },
                        new
                        {
                            AppelationId = 23,
                            Color = 2,
                            KeepMax = 20,
                            KeepMin = 8,
                            Name = "Jura"
                        },
                        new
                        {
                            AppelationId = 24,
                            Color = 2,
                            KeepMax = 5,
                            KeepMin = 4,
                            Name = "Alsace"
                        },
                        new
                        {
                            AppelationId = 25,
                            Color = 1,
                            KeepMax = 4,
                            KeepMin = 3,
                            Name = "Languedoc"
                        },
                        new
                        {
                            AppelationId = 26,
                            Color = 1,
                            KeepMax = 3,
                            KeepMin = 3,
                            Name = "Provence"
                        },
                        new
                        {
                            AppelationId = 27,
                            Color = 1,
                            KeepMax = 2,
                            KeepMin = 2,
                            Name = "Rhône"
                        });
                });

            modelBuilder.Entity("Wine_cellar.Entities.Cellar", b =>
                {
                    b.Property<int>("CellarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CellarId"));

                    b.Property<int>("Brand")
                        .HasColumnType("int");

                    b.Property<string>("BrandOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CellarType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbDrawerMax")
                        .HasColumnType("int");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CellarId");

                    b.HasIndex("UserId");

                    b.ToTable("Cellars");

                    b.HasData(
                        new
                        {
                            CellarId = 1,
                            Brand = 1,
                            CellarType = 2,
                            Name = "Cellar 1",
                            NbDrawerMax = 5,
                            Temperature = 15,
                            UserId = 2
                        },
                        new
                        {
                            CellarId = 2,
                            Brand = 10,
                            BrandOther = "ChineseBrand",
                            CellarType = 0,
                            Name = "Cellar 2",
                            NbDrawerMax = 10,
                            Temperature = 14,
                            UserId = 2
                        },
                        new
                        {
                            CellarId = 3,
                            Brand = 9,
                            CellarType = 4,
                            Name = "Cellar 3",
                            NbDrawerMax = 20,
                            Temperature = 13,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Wine_cellar.Entities.Drawer", b =>
                {
                    b.Property<int>("DrawerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrawerId"));

                    b.Property<int>("CellarId")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("NbBottleMax")
                        .HasColumnType("int");

                    b.HasKey("DrawerId");

                    b.HasIndex("CellarId");

                    b.ToTable("Drawers");

                    b.HasData(
                        new
                        {
                            DrawerId = 1,
                            CellarId = 1,
                            Index = 1,
                            NbBottleMax = 5
                        },
                        new
                        {
                            DrawerId = 2,
                            CellarId = 1,
                            Index = 2,
                            NbBottleMax = 5
                        },
                        new
                        {
                            DrawerId = 3,
                            CellarId = 1,
                            Index = 3,
                            NbBottleMax = 5
                        },
                        new
                        {
                            DrawerId = 4,
                            CellarId = 2,
                            Index = 1,
                            NbBottleMax = 5
                        },
                        new
                        {
                            DrawerId = 5,
                            CellarId = 2,
                            Index = 2,
                            NbBottleMax = 5
                        },
                        new
                        {
                            DrawerId = 6,
                            CellarId = 2,
                            Index = 3,
                            NbBottleMax = 5
                        });
                });

            modelBuilder.Entity("Wine_cellar.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@admin.com",
                            FirstName = "Admin",
                            IsAdmin = true,
                            LastName = "Admin",
                            Password = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test2@test.com",
                            FirstName = "G2",
                            IsAdmin = false,
                            LastName = "G2",
                            Password = "test2"
                        },
                        new
                        {
                            UserId = 3,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test3@test.com",
                            FirstName = "G3",
                            IsAdmin = false,
                            LastName = "G3",
                            Password = "test3"
                        });
                });

            modelBuilder.Entity("Wine_cellar.Entities.Wine", b =>
                {
                    b.Property<int>("WineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WineId"));

                    b.Property<int>("AppelationId")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("DrawerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("WineId");

                    b.HasIndex("AppelationId");

                    b.HasIndex("DrawerId");

                    b.ToTable("Wines");

                    b.HasData(
                        new
                        {
                            WineId = 1,
                            AppelationId = 1,
                            Color = 0,
                            DrawerId = 1,
                            Name = "20-1",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 2,
                            AppelationId = 2,
                            Color = 0,
                            DrawerId = 1,
                            Name = "20-2",
                            PictureName = "img/vin1.png",
                            Year = 1970
                        },
                        new
                        {
                            WineId = 3,
                            AppelationId = 3,
                            Color = 0,
                            DrawerId = 2,
                            Name = "20-3",
                            PictureName = "",
                            Year = 1980
                        },
                        new
                        {
                            WineId = 4,
                            AppelationId = 4,
                            Color = 0,
                            DrawerId = 2,
                            Name = "20-4",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 5,
                            AppelationId = 5,
                            Color = 0,
                            DrawerId = 3,
                            Name = "20-5",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 6,
                            AppelationId = 6,
                            Color = 0,
                            DrawerId = 3,
                            Name = "20-6",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 7,
                            AppelationId = 12,
                            Color = 2,
                            DrawerId = 4,
                            Name = "20-7",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 8,
                            AppelationId = 13,
                            Color = 2,
                            DrawerId = 4,
                            Name = "20-8",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 9,
                            AppelationId = 14,
                            Color = 2,
                            DrawerId = 5,
                            Name = "20-9",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 10,
                            AppelationId = 12,
                            Color = 2,
                            DrawerId = 5,
                            Name = "20-10",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 11,
                            AppelationId = 26,
                            Color = 1,
                            DrawerId = 5,
                            Name = "20-11",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 12,
                            AppelationId = 27,
                            Color = 1,
                            DrawerId = 5,
                            Name = "20-12",
                            PictureName = "",
                            Year = 1960
                        });
                });

            modelBuilder.Entity("Wine_cellar.Entities.Cellar", b =>
                {
                    b.HasOne("Wine_cellar.Entities.User", "User")
                        .WithMany("Cellars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wine_cellar.Entities.Drawer", b =>
                {
                    b.HasOne("Wine_cellar.Entities.Cellar", "Cellar")
                        .WithMany("Drawers")
                        .HasForeignKey("CellarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cellar");
                });

            modelBuilder.Entity("Wine_cellar.Entities.Wine", b =>
                {
                    b.HasOne("Wine_cellar.Entities.Appelation", "Appelation")
                        .WithMany("Wines")
                        .HasForeignKey("AppelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wine_cellar.Entities.Drawer", "Drawer")
                        .WithMany("Wines")
                        .HasForeignKey("DrawerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appelation");

                    b.Navigation("Drawer");
                });

            modelBuilder.Entity("Wine_cellar.Entities.Appelation", b =>
                {
                    b.Navigation("Wines");
                });

            modelBuilder.Entity("Wine_cellar.Entities.Cellar", b =>
                {
                    b.Navigation("Drawers");
                });

            modelBuilder.Entity("Wine_cellar.Entities.Drawer", b =>
                {
                    b.Navigation("Wines");
                });

            modelBuilder.Entity("Wine_cellar.Entities.User", b =>
                {
                    b.Navigation("Cellars");
                });
#pragma warning restore 612, 618
        }
    }
}
