// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wine_cellar.Contexts;

#nullable disable

namespace Winecelar.Migrations
{
    [DbContext(typeof(WineContext))]
    partial class WineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wine_cellar.Entities.Appelation", b =>
                {
                    b.Property<int>("AppelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppelationId"));

                    b.Property<string>("AppelationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("KeepMax")
                        .HasColumnType("int");

                    b.Property<int>("KeepMin")
                        .HasColumnType("int");

                    b.HasKey("AppelationId");

                    b.ToTable("Appelations");

                    b.HasData(
                        new
                        {
                            AppelationId = 1,
                            AppelationName = "Bordeaux",
                            Color = 0,
                            KeepMax = 10,
                            KeepMin = 5
                        },
                        new
                        {
                            AppelationId = 2,
                            AppelationName = "Loire",
                            Color = 0,
                            KeepMax = 6,
                            KeepMin = 4
                        },
                        new
                        {
                            AppelationId = 3,
                            AppelationName = "Bordeaux, Grands crus",
                            Color = 0,
                            KeepMax = 20,
                            KeepMin = 10
                        },
                        new
                        {
                            AppelationId = 4,
                            AppelationName = "Sud-Ouest",
                            Color = 0,
                            KeepMax = 10,
                            KeepMin = 5
                        },
                        new
                        {
                            AppelationId = 5,
                            AppelationName = "Languedoc & Provence",
                            Color = 0,
                            KeepMax = 8,
                            KeepMin = 5
                        },
                        new
                        {
                            AppelationId = 6,
                            AppelationName = "Côtes du Rhône",
                            Color = 0,
                            KeepMax = 6,
                            KeepMin = 4
                        },
                        new
                        {
                            AppelationId = 7,
                            AppelationName = "Cotes du Rhônes, Grands Crus",
                            Color = 0,
                            KeepMax = 20,
                            KeepMin = 10
                        },
                        new
                        {
                            AppelationId = 8,
                            AppelationName = "Beaujolais",
                            Color = 0,
                            KeepMax = 5,
                            KeepMin = 4
                        },
                        new
                        {
                            AppelationId = 9,
                            AppelationName = "Beaujolais, Crus",
                            Color = 0,
                            KeepMax = 8,
                            KeepMin = 5
                        },
                        new
                        {
                            AppelationId = 10,
                            AppelationName = "Bourgogne, Saône-et-Loire",
                            Color = 0,
                            KeepMax = 10,
                            KeepMin = 5
                        },
                        new
                        {
                            AppelationId = 11,
                            AppelationName = "Bourgogne, Côte-d'Or",
                            Color = 0,
                            KeepMax = 20,
                            KeepMin = 10
                        },
                        new
                        {
                            AppelationId = 12,
                            AppelationName = "Loire, Sec",
                            Color = 2,
                            KeepMax = 4,
                            KeepMin = 3
                        },
                        new
                        {
                            AppelationId = 13,
                            AppelationName = "Loire, moelleux et liquoreux",
                            Color = 2,
                            KeepMax = 20,
                            KeepMin = 10
                        },
                        new
                        {
                            AppelationId = 14,
                            AppelationName = "Bordeaux, sec",
                            Color = 2,
                            KeepMax = 8,
                            KeepMin = 5
                        },
                        new
                        {
                            AppelationId = 15,
                            AppelationName = "Bordeaux, liquoreux",
                            Color = 2,
                            KeepMax = 20,
                            KeepMin = 15
                        },
                        new
                        {
                            AppelationId = 16,
                            AppelationName = "Sud-Ouest, sec",
                            Color = 2,
                            KeepMax = 5,
                            KeepMin = 4
                        },
                        new
                        {
                            AppelationId = 17,
                            AppelationName = "Sud-Ouest, liquoreux",
                            Color = 2,
                            KeepMax = 15,
                            KeepMin = 10
                        },
                        new
                        {
                            AppelationId = 18,
                            AppelationName = "Languedoc & Provence",
                            Color = 2,
                            KeepMax = 3,
                            KeepMin = 3
                        },
                        new
                        {
                            AppelationId = 19,
                            AppelationName = "Côtes du Rhône",
                            Color = 2,
                            KeepMax = 4,
                            KeepMin = 3
                        },
                        new
                        {
                            AppelationId = 20,
                            AppelationName = "Bourgogne, Saône-et-Loire",
                            Color = 2,
                            KeepMax = 4,
                            KeepMin = 4
                        },
                        new
                        {
                            AppelationId = 21,
                            AppelationName = "Bourgogne, Côte-d'Or",
                            Color = 2,
                            KeepMax = 10,
                            KeepMin = 7
                        },
                        new
                        {
                            AppelationId = 22,
                            AppelationName = "Jura",
                            Color = 2,
                            KeepMax = 20,
                            KeepMin = 8
                        },
                        new
                        {
                            AppelationId = 23,
                            AppelationName = "Jura",
                            Color = 2,
                            KeepMax = 20,
                            KeepMin = 8
                        },
                        new
                        {
                            AppelationId = 24,
                            AppelationName = "Alsace",
                            Color = 2,
                            KeepMax = 5,
                            KeepMin = 4
                        },
                        new
                        {
                            AppelationId = 25,
                            AppelationName = "Languedoc",
                            Color = 1,
                            KeepMax = 4,
                            KeepMin = 3
                        },
                        new
                        {
                            AppelationId = 26,
                            AppelationName = "Provence",
                            Color = 1,
                            KeepMax = 3,
                            KeepMin = 3
                        },
                        new
                        {
                            AppelationId = 27,
                            AppelationName = "Rhône",
                            Color = 1,
                            KeepMax = 2,
                            KeepMin = 2
                        });
                });

            modelBuilder.Entity("Wine_cellar.Entities.Cellar", b =>
                {
                    b.Property<int>("CellarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CellarId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbDrawerMax")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CellarId");

                    b.HasIndex("UserId");

                    b.ToTable("Cellars");

                    b.HasData(
                        new
                        {
                            CellarId = 1,
                            Name = "Cellar 1",
                            NbDrawerMax = 5,
                            UserId = 1
                        },
                        new
                        {
                            CellarId = 2,
                            Name = "Cellar 2",
                            NbDrawerMax = 10,
                            UserId = 2
                        },
                        new
                        {
                            CellarId = 3,
                            Name = "Cellar 3",
                            NbDrawerMax = 20,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Wine_cellar.Entities.Drawer", b =>
                {
                    b.Property<int>("DrawerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrawerId"));

                    b.Property<int>("CellarId")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("NbBottleMax")
                        .HasColumnType("int");

                    b.HasKey("DrawerId");

                    b.HasIndex("CellarId");

                    b.ToTable("Drawers");

                    b.HasData(
                        new
                        {
                            DrawerId = 1,
                            CellarId = 1,
                            Index = 1,
                            NbBottleMax = 5
                        },
                        new
                        {
                            DrawerId = 2,
                            CellarId = 1,
                            Index = 2,
                            NbBottleMax = 5
                        },
                        new
                        {
                            DrawerId = 3,
                            CellarId = 1,
                            Index = 3,
                            NbBottleMax = 5
                        },
                        new
                        {
                            DrawerId = 4,
                            CellarId = 2,
                            Index = 1,
                            NbBottleMax = 5
                        },
                        new
                        {
                            DrawerId = 5,
                            CellarId = 2,
                            Index = 2,
                            NbBottleMax = 5
                        },
                        new
                        {
                            DrawerId = 6,
                            CellarId = 2,
                            Index = 3,
                            NbBottleMax = 5
                        });
                });

            modelBuilder.Entity("Wine_cellar.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test@test.com",
                            FirstName = "G",
                            LastName = "G",
                            Password = "test"
                        },
                        new
                        {
                            UserId = 2,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test2@test.com",
                            FirstName = "G2",
                            LastName = "G2",
                            Password = "test2"
                        },
                        new
                        {
                            UserId = 3,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test3@test.com",
                            FirstName = "G3",
                            LastName = "G3",
                            Password = "test3"
                        });
                });

            modelBuilder.Entity("Wine_cellar.Entities.Wine", b =>
                {
                    b.Property<int>("WineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WineId"));

                    b.Property<int>("AppelationId")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("DrawerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("WineId");

                    b.HasIndex("AppelationId");

                    b.HasIndex("DrawerId");

                    b.ToTable("Wines");

                    b.HasData(
                        new
                        {
                            WineId = 1,
                            AppelationId = 1,
                            Color = 0,
                            DrawerId = 1,
                            Name = "20-1",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 2,
                            AppelationId = 2,
                            Color = 0,
                            DrawerId = 1,
                            Name = "20-2",
                            PictureName = "img/vin1.png",
                            Year = 1970
                        },
                        new
                        {
                            WineId = 3,
                            AppelationId = 3,
                            Color = 0,
                            DrawerId = 2,
                            Name = "20-3",
                            PictureName = "",
                            Year = 1980
                        },
                        new
                        {
                            WineId = 4,
                            AppelationId = 4,
                            Color = 0,
                            DrawerId = 2,
                            Name = "20-4",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 5,
                            AppelationId = 5,
                            Color = 0,
                            DrawerId = 3,
                            Name = "20-5",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 6,
                            AppelationId = 6,
                            Color = 0,
                            DrawerId = 3,
                            Name = "20-6",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 7,
                            AppelationId = 12,
                            Color = 2,
                            DrawerId = 4,
                            Name = "20-7",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 8,
                            AppelationId = 13,
                            Color = 2,
                            DrawerId = 4,
                            Name = "20-8",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 9,
                            AppelationId = 14,
                            Color = 2,
                            DrawerId = 5,
                            Name = "20-9",
                            PictureName = "",
                            Year = 1960
                        },
                        new
                        {
                            WineId = 10,
                            AppelationId = 12,
                            Color = 2,
                            DrawerId = 5,
                            Name = "20-10",
                            PictureName = "",
                            Year = 1960
                        });
                });

            modelBuilder.Entity("Wine_cellar.Entities.Cellar", b =>
                {
                    b.HasOne("Wine_cellar.Entities.User", "User")
                        .WithMany("Cellars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wine_cellar.Entities.Drawer", b =>
                {
                    b.HasOne("Wine_cellar.Entities.Cellar", "Cellar")
                        .WithMany("Drawers")
                        .HasForeignKey("CellarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cellar");
                });

            modelBuilder.Entity("Wine_cellar.Entities.Wine", b =>
                {
                    b.HasOne("Wine_cellar.Entities.Appelation", "Appelation")
                        .WithMany("Wines")
                        .HasForeignKey("AppelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wine_cellar.Entities.Drawer", "Drawer")
                        .WithMany("Wines")
                        .HasForeignKey("DrawerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appelation");

                    b.Navigation("Drawer");
                });

            modelBuilder.Entity("Wine_cellar.Entities.Appelation", b =>
                {
                    b.Navigation("Wines");
                });

            modelBuilder.Entity("Wine_cellar.Entities.Cellar", b =>
                {
                    b.Navigation("Drawers");
                });

            modelBuilder.Entity("Wine_cellar.Entities.Drawer", b =>
                {
                    b.Navigation("Wines");
                });

            modelBuilder.Entity("Wine_cellar.Entities.User", b =>
                {
                    b.Navigation("Cellars");
                });
#pragma warning restore 612, 618
        }
    }
}
